### ISSUE TITLE
[BUG] Event Processors mega-issue

### ISSUE THREAD

**Issue by LordOfPolls** [NAFTeam/NAFF#259]
Dump of flaws, discussed in contributors channel, found in the event processors. I'll check off each of these as theyre resolved

- [x] ~~`_on_raw_channel_delete` does not delete channel from cache, it shoud~~ -- Fixed in c57c3d73a78774fe633d383155c0afc4a4e840df
- [x] ~~`_on_raw_guild_delete` Unresolved attribute reference 'user' for class 'GuildEvents'~~ Fixed in 4ca84782134a8502c46e34627b4fe054ca06c9bb
- [x] ~~`_on_raw_guild_delete` does not delete guild from cache~~ Fixed in 3576ab264dd6035a2b21d642cc013619a5f901e2
- [x] ~~`_on_raw_guild_delete` should iterate through users and remove guild ids from sets in cache.user_guilds~~ Fixed in 3576ab264dd6035a2b21d642cc013619a5f901e2
- [x] ~~`_on_raw_guild_delete`  event.data.get("id") should be int(event.data.get("id")).~~ Fixed in b4376fe5faf1b9d20fac759972012bb08bcf469d
- [x] `_on_raw_guild_ban_add`,` _on_raw_guild_ban_remove` should update members obj, or members set in guild or something
- [x] ~~`_on_raw_guild_emojis_update` for the love of god make before and after proper variables, that's unradable~~ Fixed in 483809cb4c2a508ef0cdfb84bb7b773f4ae36b88
- [x] ~~`_on_raw_message_delete` does not delete message from cache~~ Fixed in 310c3a881821f00b5cb935bc71ca7b396ef05ca2
- [x] `_on_raw_thread_delete` does not delete threads from cache
- [ ] There are also inconsistencies and wrong typing/naming in discord event classes themselves

Please tag this issue in your commits/prs if they fix something here

**Comment by LordOfPolls** [comment]
not fixing this as it would be more useful to keep it in the cache. Bots with uncapped message caches would want to keep deleted messages, bots with TTLCaches wont care if we delete it or not

> `_on_raw_message_delete` does not delete message from cache

**Comment by artem30801** [comment]
> not fixing this as it would be more useful to keep it in the cache. Bots with uncapped message caches would want to keep deleted messages, bots with TTLCaches wont care if we delete it or not
> 
> > `_on_raw_message_delete` does not delete message from cache

Then we should have an attribute or some other indication to convey that the message was deleted

**Comment by AstreaTSS** [comment]
> not fixing this as it would be more useful to keep it in the cache. Bots with uncapped message caches would want to keep deleted messages, bots with TTLCaches wont care if we delete it or not
> 
> > `_on_raw_message_delete` does not delete message from cache

Honestly, I'm going to disagree here. Bots with uncapped message caches might not necessarily *want* deleted messages, simply just wanting an easy way to have all "alive" messages for stuff (for example, a starboard bot may want every message to be kept so reaction events work faster, but having deleted messages would be a waste since they're not being reacted to).

Personally, I can't think of many cases where you would *want* deleted messages (for longer than the MessageDelete event), even with an uncapped cache. Sniping, I guess? They can cache that themselves for their own purposes (and I say this as someone who's made sniping stuff), hooking onto the delete event, which *should* be right before the message is deleted from the cache ideally. And honestly, I feel like there's more cases where we *don't* want a deleted message over where we do.

And even with the TTL cache, you still *kinda* do wanna do that since you don't want to accidentally get a deleted message. For a personal example, in one of my bots (a starboard one, I'll admit my examples are limited lol), you can specify a message ID (among other methods) to force star a message. Getting a (presumably recently) deleted message there would be awkward at the very least.

Sure, a property/attribute would be *nice*, but it's an extra check to something I don't see as very useful.
There's probably some *very* valid reason to have deleted messages in the cache that I'm missing. But even if they exist, I feel like at the *very* least, deleting messages from the cache should be on at default, with maybe a toggle to turn that off.

**Comment by AlbertUnruh** [comment]
I don't know whether this should be appended here or in another issue or not, but I run into an 
``AttributeError: 'set' object has no attribute 'append'``
(coro ``ChannelEvents._on_raw_channel_create`` in file ``dis_snek/event_processors/channel_events.py:18``)

**Comment by leestarb** [comment]
> I don't know whether this should be appended here or in another issue or not, but I run into an 
> ``AttributeError: 'set' object has no attribute 'append'``
> (coro ``ChannelEvents._on_raw_channel_create`` in file ``dis_snek/event_processors/channel_events.py:18``)

Which version do you use? Its probably fixed in 6.0.0

**Comment by AlbertUnruh** [comment]
> > I don't know whether this should be appended here or in another issue or not, but I run into an
> > `AttributeError: 'set' object has no attribute 'append'`
> > (coro `ChannelEvents._on_raw_channel_create` in file `dis_snek/event_processors/channel_events.py:18`)
> 
> Which version do you use? Its probably fixed in 6.0.0

Oh, nvm, I was using v3.0.0 with Python 3.9... (I thought I was using the latest version from pip)
I'll go and upgrade to 3.10.

**Comment by LordOfPolls** [comment]
re
>  `_on_raw_guild_ban_add`, `_on_raw_guild_ban_remove` should update members obj, or members set in guild or something

We dont cache ban lists or ban states in guilds or member objects. Adding that functionality is out-of-scope of this issue, skipping

**Comment by LordOfPolls** [comment]
re
> There are also inconsistencies and wrong typing/naming in discord event classes themselves

I cant see where this is the case, examples would be nice.
